### ISSUE TITLE
Cant make 1 long wire

### ISSUE THREAD

**Issue by ShortsKing** [ashleynewson/SmartSim#14]
i am unable to make a wire that is 1 long

**Comment by ashleynewson** [comment]
Your issue is somewhat vague, but hopefully the following tips will help:

- You can definitely create 1 unit long wires.
- It is easiest to create such wires after zooming in with the Zoom tool.
- When clicking near the pins of components, SmartSim will try to snap onto these pins when using the wire tool. If you click on a grid point next to the pin, it's going to snap. If you click slightly further away from the pin (such as 1.4 grid points away), it won't snap to the pin.
- If you have two pins close together, the tool will snap to the closer pin.
- If the next point in the wire being placed is almost vertical or horizontal with the previous point, the previous point will be adjusted to be in line vertically of horizontally. (Unless the previous point was the first point)
